### ISSUE TITLE
problem in getting the right sam file

### ISSUE THREAD

**Issue by AfredComma** [christophertbrown/iRep#11]
Hello,
I'm trying to use iRep to repeat the work of Measurement of bacterial replication rates in microbial communities . I downloaded the SRA files of premature human infant (SRP052967) and transformed SRR1779101.sra to fastq file by sratoolkit, then chose Clostridium perfringens genome to calculate the iRep values. By using the bowtie2.2.1, I got the sam file, but the iRep value is n/a (un-filtered index of replication is 10.64). 

My bowtie2 scripts are:
bowtie2-2.2.1/bowtie2-build Clostridium perfringens.fna cp_index
bowtie2-2.2.1/bowtie2-align-s --wrapper basic-0 -x cp_index -p 6 --very-fast --reorder --quiet -U ../sambulid2/SRR1779101.fastq -S SRR1779101_cp.sam

Few quenstions:
1. Is  "--wrapper basic-0" essential for the sam file building?
2. Is the version of bowtie2-2.2.1 outdated?
3. Can we use the big sam file without running shrinksam to compute the iRep values?

Thanks,
CommaD

**Comment by christophertbrown** [comment]
Hi CommaD,

Since you are getting an un-filtered iRep value, it sounds to me like the mapping is working correctly. Usually you get a 'n/a' value when either the genome coverage is too low, or there is a poor fit to the coverage data when iRep is being calculated. This happens when the genome used for mapping is not a close match to the genome of an organism present in the sample, when it is low abundance, and sometimes due to strain variation. 

For that sample, I would recommend using any of these genomes, which can be downloaded from http://ggkbase.berkeley.edu:
NECEvent2014_10_1_Escherichia_coli_52_196
NECEvent2014_10_1_Lactobacillus_crispatus_36_608
NECEvent2014_10_1_Lactobacillus_gasseri_34_15

Then, you can compare the results to those in Supplementary Table 5.

Hope this helps. Let me know if you still have questions. 

Chris
