### ISSUE TITLE
iRep for long reads

### ISSUE THREAD

**Issue by mdrishti** [christophertbrown/iRep#30]
Hi,

I have some metgenomics samples with long reads and also the complete genomes of the microbes that I want the replication rates for.
I am wondering if iRep/bPTR could be applied to metagenomics data obtained via long read sequencing technologies (PacBio and Nanopore). If yes, then would there be any bias introduced in the results because of the high error rates?

**Comment by christophertbrown** [comment]
In principle both methods should work with long reads. However, you bring up a good point with regards to the error rate, which will be especially important if there are multiple closely related strains that you need to distinguish based on only a few SNPs. If that is not the case, then it should actually work quite well as the longer reads should be less likely to map to the wrong genome (i.e. genome from different species), which is the largest source of error with these methods. 

Since you have complete genomes bPTR may be easier to analyze. After running iRep/bPTR you can probably get a sense of the quality of the analysis from the plots produced by both scripts.
