### ISSUE TITLE
iRep and bPTR values lower than one

### ISSUE THREAD

**Issue by yilmazbah** [christophertbrown/iRep#32]
Dear all, 
When we analyzed our dataset using your pipeline, we got values lower than 1 for samples in bPTR analysis. Can you explain me what is the meaning of having values lower than one both for iRep and bPTR? Any thought will be useful. Thank you so much. 
Best wishes,
Bahti

**Comment by christophertbrown** [comment]
Hi Bahti,

Values lower than one are an artifact of the PTR method. This happens when coverage at the origin and terminus are very similar, and random variation in coverage causes the terminus to be higher than at the origin. It also indicates that there may have been an issue correctly identifying the location of the origin and/or terminus of replication. 

iRep is calculated differently, and as such it is not possible to have values lower than one. Values of one, or close to it, indicate a lack of replication. 

Hope this helps! 

Chris

**Comment by yilmazbah** [comment]
Hey Chris,

Thank you so much for your help and explanation. This is really helpful. I think those samples of mine should be lack of replication.

Thanks a lot for your time.

All the best,
Bahti
